[package]
edition = "2018"
name = "stardust-xr"
version = "0.9.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libstardustxr = {path = "../libstardustxr-rs"}
anyhow = "1.0.57"
ctrlc = "3.2.2"
mio = {version = "0.8.3", features = ["net", "os-poll", "os-ext"]}
slab = "0.4.6"
thiserror = "1.0.31"
